eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

springdoc:
  api-docs:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"